export const TIME_CONSTANTS = {
  MILLISECONDS_IN_SECOND: 1000,
  SECONDS_IN_MINUTE: 60,
  MINUTES_IN_HOUR: 60,
  HOURS_IN_DAY: 24,
  DAYS_IN_WEEK: 7,
  DAYS_IN_MONTH: 30,
  DAYS_IN_TWO_WEEKS: 14,
} as const;

export const STATS_CONSTANTS = {
  ACTIVITY_DAYS: 49,
  HOURS_IN_DAY: 24,
  RECENT_ATTEMPTS_LIMIT: 10,
  TOP_WEAK_TOPICS_LIMIT: 5,
  WEAK_TOPIC_THRESHOLD: 70,
  MIN_TOPIC_ATTEMPTS: 2,
  SEARCH_RESULTS_LIMIT: 10,
  LEADERBOARD_DEFAULT_LIMIT: 50,
  MINUTES_PER_QUESTION: 2,
  DEFAULT_QUESTION_COUNT: 10,
  MIN_SEARCH_QUERY_LENGTH: 2,
} as const;

export const PREDICTION_CONSTANTS = {
  MIN_TESTS_FOR_PREDICTION: 3,
  RECENT_SCORES_LIMIT: 20,
  EXPONENTIAL_DECAY: 0.15,
  MOMENTUM_WEIGHT: 0.5,
  RECENT_BOOST_WEIGHT: 0.3,
  FREQUENCY_BONUS: 5,
  CONSISTENCY_THRESHOLD: 70,
  CONSISTENCY_BONUS: 3,
  BASE_CONFIDENCE: 50,
  CONFIDENCE_MAX: 95,
  MOMENTUM_POSITIVE_THRESHOLD: 5,
  MOMENTUM_NEGATIVE_THRESHOLD: -5,
  FREQUENCY_THRESHOLD: 0.5,
  STREAK_THRESHOLD: 3,
  MAX_SCORE_DIFF: 15,
  MIN_RECENT_SCORES: 3,
  FIRST_SCORES_COUNT: 5,
  LAST_SCORES_COUNT: 5,
  CONSISTENCY_VARIANCE_MULTIPLIER: 2,
  CONSISTENCY_MAX_SCORE: 100,
  FREQUENCY_DAYS_DIVISOR: 30,
  CONFIDENCE_TEST_THRESHOLD: 10,
  CONFIDENCE_PER_TEST: 2,
  CONFIDENCE_CONSISTENCY_BONUS: 15,
  CONFIDENCE_CONSISTENCY_THRESHOLD: 60,
  CONFIDENCE_FREQUENCY_MULTIPLIER: 10,
  MAX_SCORE: 100,
} as const;

export const SCORING_CONSTANTS = {
  DECIMAL_PRECISION: 10,
  PERCENTAGE_MULTIPLIER: 100,
  TESTS_MULTIPLIER: 10,
  AVERAGE_MULTIPLIER: 5,
  BEST_SCORE_MULTIPLIER: 2,
  ACHIEVEMENT_MULTIPLIER: 50,
} as const;

export const HTTP_STATUS = {
  OK: 200,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
} as const;

export const ERROR_MESSAGES = {
  UNAUTHORIZED: 'Не авторизован',
  USER_NOT_FOUND: 'Пользователь не найден',
  AVATAR_REQUIRED: 'Аватар не указан',
  INVALID_PRIVACY: 'Некорректное значение приватности',
  PROFILE_PRIVATE: 'Этот профиль приватный',
  ACHIEVEMENTS_CHECKED: 'Достижения проверены',
} as const;

export const DEFAULT_VALUES = {
  FAVORITE_SUBJECT: 'MATHEMATICS',
  LEADERBOARD_PERIOD: 'all',
  LEADERBOARD_SUBJECT: 'all',
  PERCENTILE: 50,
} as const;
